DROP TABLE ADMIN;

CREATE TABLE ADMIN(
    AID VARCHAR2(30) PRIMARY KEY,
    APW VARCHAR2(30) NOT NULL,
    ANAME VARCHAR2(30) NOT NULL
);
 INSERT INTO ADMIN VALUES ('admin', 'admin', '오성현');

-- 로그인 
SELECT * FROM ADMIN WHERE AID='admin' AND APW='admin';

SELECT * FROM ADMIN WHERE AID='admin';
COMMIT;