DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    MID      VARCHAR2(30) PRIMARY KEY, --이름
    MPW      VARCHAR2(30) NOT NULL,  
    MNAME    VARCHAR2(30) NOT NULL,
    MADDRESS VARCHAR2(255),
    MTEL     VARCHAR2(30) NOT NULL,
    MEMAIL   VARCHAR2(30) NOT NULL,
    MBIRTH   DATE,
    MRDATE   DATE DEFAULT SYSDATE,
    MSTATE   NUMBER(1) DEFAULT 0
);
-- mId 중복체크
SELECT * FROM MEMBER WHERE MID='aaa123';
-- 회원가입
INSERT INTO MEMBER (MID,MPW,MNAME,MADDRESS,MTEL,MEMAIL,MBIRTH)
        VALUES ('aaa123','aaa123','오성현','서울시 종루구','01049337210','ses2155@gmail.com','1999/12/12');

INSERT INTO MEMBER (MID,MPW,MNAME,MADDRESS,MTEL,MEMAIL,MBIRTH)
        VALUES ('bbb','111','김성현','서울시 종루구','010-4933-7210','ses2155@gmail.com','1999/12/12');

INSERT INTO MEMBER (MID,MPW,MNAME,MADDRESS,MTEL,MEMAIL,MBIRTH)
        VALUES ('ccc','111','나성현','서울시 종루구','010-4933-7210','ses2155@gmail.com','1999/12/12');
INSERT INTO MEMBER (MID,MPW,MNAME,MADDRESS,MTEL,MEMAIL)
        VALUES ('ddd','111','나성현','서울시 종루구','010-4933-7210','ses2155@gmail.com');
-- 로그인 (mID, mPW. mState)
SELECT * FROM MEMBER WHERE MID='aaa123' AND MPW='aaa123' AND MSTATE = 0;
--세션에 넣기 위해 mId로 member dto가져오기
SELECT * FROM MEMBER WHERE MID='aaa';
--회원정보수정 (MPW, MADDRESS, MTEL, MEMAIL / MID)
UPDATE MEMBER SET MPW='222', MADDRESS='서울시 동대문구', MTEL='010-3333-3333', MEMAIL='ggg2155@gmail.com' 
    WHERE MID='aaa';

-- 회원목록(startRow ~ endRow) 
SELECT * FROM MEMBER WHERE MSTATE=0 ORDER BY  MRDATE DESC;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM
        (SELECT * FROM MEMBER WHERE MSTATE=0 ORDER BY MRDATE DESC )A)
        WHERE RN BETWEEN 1 AND 10;


-- 가입한 회원 명수
SELECT COUNT(*) FROM MEMBER WHERE MSTATE=0;

-- 탈퇴한 회원목록(startRow ~ endRow) 
SELECT * FROM MEMBER WHERE MSTATE=1 ORDER BY  MRDATE DESC;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM
        (SELECT * FROM MEMBER WHERE MSTATE=1 ORDER BY MRDATE DESC )A)
        WHERE RN BETWEEN 1 AND 10;


-- 탈퇴한 회원 명수
SELECT COUNT(*) FROM MEMBER WHERE MSTATE=1;
-- 회원 삭제

UPDATE MEMBER SET MSTATE = 1 WHERE MID='aaa123';


commit;




