DROP TABLE NOTICE_BOARD;
DROP SEQUENCE NOTICE_BOARD_SEQ;
CREATE TABLE NOTICE_BOARD(
    NNO NUMBER(9) PRIMARY KEY,
    AID VARCHAR2(30) REFERENCES ADMIN (AID),
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(4000),
    NRDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(6) DEFAULT 0
);

CREATE SEQUENCE NOTICE_BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
-- 더미데이터
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');

SELECT * FROM NOTICE_BOARD;

-- 글목록 (startRow ~ endRow) // 글번호 글제목 이름 글쓴날짜
SELECT N.*, ANAME FROM NOTICE_BOARD N, ADMIN A WHERE A.AID=N.AID ORDER BY NNO DESC;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM
    (SELECT N.*, ANAME FROM NOTICE_BOARD N, ADMIN A WHERE A.AID=N.AID ORDER BY NNO DESC)A)
    WHERE RN BETWEEN 1 AND 10;
-- 글개수
SELECT COUNT(*) FROM NOTICE_BOARD;    
-- 글쓰기 
INSERT INTO  NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) 
    VALUES (NOTICE_BOARD_SEQ.NEXTVAL, 'admin','제목','내용');
-- 조회수 올리기
UPDATE NOTICE_BOARD SET NHIT = NHIT+1 WHERE NNO='13';
-- NNO로 글 dto보기
SELECT N.*, ANAME FROM NOTICE_BOARD N, ADMIN A WHERE A.AID=N.AID AND NNO='3';
-- 글수정하기
UPDATE NOTICE_BOARD SET NTITLE='바뀜',NCONTENT='바뀜', NRDATE=SYSDATE WHERE NNO='13';
-- 글삭제하기
DELETE FROM NOTICE_BOARD WHERE NNO='13';


