DROP TABLE PRODUCT;
DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ MAXVALUE 999 NOCACHE NOCYCLE;
CREATE TABLE PRODUCT(
    PCODE VARCHAR2(30) PRIMARY KEY,
    PNAME VARCHAR2(30) NOT NULL,
    PTYPE VARCHAR2(30) NOT NULL,
    PFILENAME VARCHAR2(100) NOT NULL,
    PORIGN VARCHAR2(30) NOT NULL,
    PWEIGHT VARCHAR2(30) NOT NULL,
    PPART VARCHAR2(30) NOT NULL,
    PUSE VARCHAR2(30) NOT NULL,
    PPRICE NUMBER(9) NOT NULL,
    PSTOCK NUMBER(9) NOT NULL,
    PRDATE DATE DEFAULT SYSDATE    
);
SELECT * FROM PRODUCT;
-- 상품코드, 상품명, 상품타입(PORK,BEEP), 상품첨부파일이름, 원산지, 중량, 부위, 용도, 단가, 재고수량

-- 상품등록
INSERT INTO PRODUCT (PCODE,PNAME,PTYPE,PFILENAME,PORIGN,PWEIGHT,PPART,PUSE,PPRICE,PSTOCK) 
    VALUES ('GOGI'||TRIM(TO_CHAR(PRODUCT_SEQ.nextval,'000')),
        'LA갈비','beef','BEEP_C.jpg','한국','100g','갈비','구이용/찜용', 45000, 10);
INSERT INTO PRODUCT (PCODE,PNAME,PTYPE,PFILENAME,PORIGN,PWEIGHT,PPART,PUSE,PPRICE,PSTOCK) 
    VALUES ('GOGI'||TRIM(TO_CHAR(PRODUCT_SEQ.nextval,'000')),
        'LA갈비','pork','BEEP_B.jpg','한국','100g','갈비','구이용/찜용', 45000, 10);         



INSERT INTO PRODUCT (PCODE,PNAME,PTYPE,PFILENAME,PORIGN,PWEIGHT,PPART,PUSE,PPRICE,PSTOCK) 
    VALUES ('GOGI'||TRIM(TO_CHAR(PRODUCT_SEQ.nextval,'000')),'LA갈비','pork','BEEP_F.jpg','한국','100g','갈비','구이용/찜용', 4500, 10000);
INSERT INTO PRODUCT (PCODE,PNAME,PTYPE,PFILENAME,PORIGN,PWEIGHT,PPART,PUSE,PPRICE,PSTOCK) 
    VALUES ('GOGI'||TRIM(TO_CHAR(PRODUCT_SEQ.nextval,'000')),'LA갈비','pork','BEEP_F.jpg','한국','100g','갈비','구이용/찜용', 4500, 10000);
--------------------------------

-- 상품 목록 최근순 (페이징 ) 돼지고기/ 소고기

SELECT * FROM PRODUCT WHERE PTYPE='beep' ORDER BY PRDATE DESC; 
SELECT * FROM (SELECT ROWNUM RN, A.* FROM
    (SELECT * FROM PRODUCT WHERE PTYPE='pork' ORDER BY PRDATE DESC)A) WHERE RN BETWEEN 1 AND 18;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM
    (SELECT * FROM PRODUCT ORDER BY PRDATE DESC)A) WHERE RN BETWEEN 1 AND 10;
-- 전체 상품 개수
SELECT COUNT(*) FROM PRODUCT;

-- 타입별 상품 개수

SELECT COUNT(*) FROM PRODUCT WHERE PTYPE='pork';
-- PCODE 로 가져오기 
SELECT * FROM PRODUCT WHERE PCODE='GOGI009';

-- 상품 수정
UPDATE PRODUCT SET 
    PNAME='LA갈비', PTYPE='pork',PFILENAME='BEEP_F.jsp',PORIGN='한국',PWEIGHT='100g',PPART='갈비',PUSE='구이용',PPRICE='4000',PSTOCK='500' WHERE PCODE='GOGI009';

-- 상품 삭제 

DELETE FROM PRODUCT WHERE PCODE='GOGI010';

-- 주문시 재고수량 변경
UPDATE PRODUCT SET PSTOCK=PSTOCK-10 WHERE PCODE='GOGI025';




COMMIT;



