DROP TABLE QNA;
DROP SEQUENCE QNA_SEQ;
CREATE TABLE QNA(
    QNO NUMBER(9) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    AID VARCHAR2(30) REFERENCES ADMIN(AID),
    QTITLE VARCHAR2(100) NOT NULL,
    QCONTENT VARCHAR2(4000),
    QFILENAME1 VARCHAR2(100),
    QFILENAME2 VARCHAR2(100),
    QGROUP NUMBER(6) NOT NULL,
    QSTEP NUMBER(6) NOT NULL,
    QINDENT NUMBER(6) NOT NULL,
    QHIT NUMBER(6) DEFAULT 0,
    QRDATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE QNA_SEQ MAXVALUE 999 NOCACHE NOCYCLE;

SELECT * FROM QNA;

INSERT INTO QNA (QNO, MID, AID, QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, 'aaa123', null, '제목', '내용', null, null, QNA_SEQ.CURRVAL, 0, 0 );

INSERT INTO QNA (QNO, MID, AID, QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, NULL, 'admin', '제목', '내용', null, null, QNA_SEQ.CURRVAL, 0, 0);
    
    
-- 글목록

SELECT QNO, (SELECT MNAME FROM QNA Q, MEMBER M WHERE Q.MID=M.MID AND QNA.QNO=QNO) ||
    (SELECT ANAME FROM QNA Q, ADMIN M WHERE Q.AID=M.AID AND QNA.QNO=QNO) WRITER, 
   QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT, QHIT, QRDATE
   FROM QNA ORDER BY QGROUP DESC, QSTEP;
   
SELECT * FROM (SELECT ROWNUM RN, A.* FROM 
    (SELECT QNO, (SELECT MNAME FROM QNA Q, MEMBER M 
        WHERE Q.MID=M.MID AND QNA.QNO=QNO) ||
    (SELECT ANAME FROM QNA Q, ADMIN M 
        WHERE Q.AID=M.AID AND QNA.QNO=QNO) WRITER, MID, AID, 
        QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT, QHIT, QRDATE
        WHERE RN BETWEEN 1 AND 10;

-- 글 개수 

SELECT COUNT(*) FROM QNA;

-- 글 쓰기(원글) 
INSERT INTO QNA (QNO, MID, AID, QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, 'aaa123', null, '제목', '내용', null, null, QNA_SEQ.CURRVAL, 0, 0 );
    
-- 글 조회수 올리기
UPDATE QNA SET QHIT = QHIT+1 WHERE QNO='1';

-- 글 수정하기

UPDATE QNA SET QTITLE='바뀐제목', QCONTENT='바뀐내용', QFILENAME1=null, QFILENAME2=null, QRDATE=SYSDATE
    WHERE QNO='1';

-- QNO 로 DTO 보기 (상세보기)
SELECT QNO, (SELECT MNAME FROM QNA Q, MEMBER M WHERE Q.MID=M.MID AND QNA.QNO=QNO) ||
    (SELECT ANAME FROM QNA Q, ADMIN M WHERE Q.AID=M.AID AND QNA.QNO=QNO) WRITER, MID, AID,
   QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT, QHIT, QRDATE
   FROM QNA WHERE QNO='3';
   


-- 답변글 수행전 STEP A 수행 

UPDATE QNA SET QSTEP = QSTEP+1 WHERE QGROUP=4 AND QSTEP>0;

-- 답변글 쓰기
INSERT INTO QNA 
    (QNO, MID, AID, QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, 'aaa123', null, '제목', '내용', null, null, 1, 1, 1 );

-- 글 삭제하기 

UPDATE QNA SET QSTATE = 1 WHERE QNO=5;

commit;






   


